spring:
  application:
    name: rider-service
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb
  jpa:
    hibernate:
      ddl-auto: create-drop

server :
  port: 8087